apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcp-workload-identity-federation-webhook.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gcp-workload-identity-federation-webhook.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcp-workload-identity-federation-webhook.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
  {{- include "gcp-workload-identity-federation-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "gcp-workload-identity-federation-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "gcp-workload-identity-federation-webhook.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- if .Values.controllerManager.tolerations }}
      tolerations:
      {{- toYaml .Values.controllerManager.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.controllerManager.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.controllerManager.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml .Values.controllerManager.affinity | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        {{- if .Values.controllerManager.manager.args }}
        {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        {{- end }}
        command:
        - /gcp-workload-identity-federation-webhook
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          |  default (printf "v%v" .Chart.AppVersion) }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          protocol: TCP
          name: metrics
        resources: {{- toYaml .Values.controllerManager.kubeRbacProxy.resources | nindent
          10 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "gcp-workload-identity-federation-webhook.fullname"
        . }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
