apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gcp-workload-identity-federation-webhook.fullname" . }}-manager-role
  labels:
  {{- include "gcp-workload-identity-federation-webhook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gcp-workload-identity-federation-webhook.fullname" . }}-manager-rolebinding
  labels:
  {{- include "gcp-workload-identity-federation-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gcp-workload-identity-federation-webhook.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gcp-workload-identity-federation-webhook.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
