apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "gcp-workload-identity-federation-webhook.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gcp-workload-identity-federation-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
